import { getConnection } from "../config/db.js";

/**
 * Migración 005:
 * - Agrega MONTO_SUGERIDO a SERVICIOS_CATALOGO
 * - Inserta tipos de servicio faltantes
 * - Crea tabla ESPECIALISTAS
 * - Crea tabla CONFIGURACION (clave-valor)
 * - Inserta valores de configuración iniciales
 */
export async function runMigration005() {
  let conn;
  try {
    conn = await getConnection();

    // ── 1. MONTO_SUGERIDO en SERVICIOS_CATALOGO ──────────────────────────────
    const { rows: r1 } = await conn.execute(
      `SELECT COUNT(*) AS CNT FROM USER_TAB_COLUMNS
       WHERE TABLE_NAME='SERVICIOS_CATALOGO' AND COLUMN_NAME='MONTO_SUGERIDO'`
    );
    if ((r1[0]?.CNT ?? 0) === 0) {
      await conn.execute(`ALTER TABLE SERVICIOS_CATALOGO ADD MONTO_SUGERIDO NUMBER(10,2)`);
      console.log("[migration-005] ✅ Columna MONTO_SUGERIDO agregada a SERVICIOS_CATALOGO.");
    }

    // Actualizar montos de tipos existentes
    const montos = [
      { id: 1, monto: 300 },
      { id: 2, monto: 250 },
      { id: 3, monto: 150 },
      { id: 4, monto: 0   },
    ];
    for (const { id, monto } of montos) {
      await conn.execute(
        `UPDATE SERVICIOS_CATALOGO SET MONTO_SUGERIDO = :monto WHERE ID_TIPO_SERVICIO = :id`,
        { monto, id },
        { autoCommit: true }
      );
    }

    // Insertar tipos faltantes
    const faltantes = [
      { id: 5, nombre: "Paquete de Pañales", monto: 200 },
      { id: 6, nombre: "Silla de Ruedas",    monto: 1200 },
      { id: 7, nombre: "Otros",              monto: null },
    ];
    for (const { id, nombre, monto } of faltantes) {
      const { rows: exists } = await conn.execute(
        `SELECT COUNT(*) AS CNT FROM SERVICIOS_CATALOGO WHERE ID_TIPO_SERVICIO = :id`,
        { id }
      );
      if ((exists[0]?.CNT ?? 0) === 0) {
        await conn.execute(
          `INSERT INTO SERVICIOS_CATALOGO (ID_TIPO_SERVICIO, NOMBRE, MONTO_SUGERIDO)
           VALUES (:id, :nombre, :monto)`,
          { id, nombre, monto: monto ?? null },
          { autoCommit: true }
        );
        console.log(`[migration-005] ✅ Tipo de servicio insertado: ${nombre}`);
      }
    }

    // ── 2. Tabla ESPECIALISTAS ────────────────────────────────────────────────
    const { rows: r2 } = await conn.execute(
      `SELECT COUNT(*) AS CNT FROM USER_TABLES WHERE TABLE_NAME='ESPECIALISTAS'`
    );
    if ((r2[0]?.CNT ?? 0) === 0) {
      await conn.execute(`
        CREATE TABLE ESPECIALISTAS (
          ID_ESPECIALISTA NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          NOMBRE          VARCHAR2(150) NOT NULL,
          ESPECIALIDAD    VARCHAR2(100),
          ACTIVO          NUMBER(1,0) DEFAULT 1
        )
      `);
      // Insertar especialistas iniciales
      const especialistas = [
        { nombre: "Dr. Roberto Méndez",   especialidad: "Neurología"       },
        { nombre: "Dra. Patricia Solís",  especialidad: "Rehabilitación"   },
        { nombre: "Lic. Carmen Ruiz",     especialidad: "Psicología"       },
        { nombre: "Dr. Miguel Torres",    especialidad: "Urología"         },
      ];
      for (const e of especialistas) {
        await conn.execute(
          `INSERT INTO ESPECIALISTAS (NOMBRE, ESPECIALIDAD) VALUES (:nombre, :especialidad)`,
          { nombre: e.nombre, especialidad: e.especialidad },
          { autoCommit: true }
        );
      }
      console.log("[migration-005] ✅ Tabla ESPECIALISTAS creada con datos iniciales.");
    }

    // ── 3. Tabla CONFIGURACION ────────────────────────────────────────────────
    const { rows: r3 } = await conn.execute(
      `SELECT COUNT(*) AS CNT FROM USER_TABLES WHERE TABLE_NAME='CONFIGURACION'`
    );
    if ((r3[0]?.CNT ?? 0) === 0) {
      await conn.execute(`
        CREATE TABLE CONFIGURACION (
          CLAVE       VARCHAR2(100) PRIMARY KEY,
          VALOR       VARCHAR2(500) NOT NULL,
          DESCRIPCION VARCHAR2(250)
        )
      `);
      const configs = [
        { clave: "MONTO_MEMBRESIA_MENSUAL", valor: "500",               desc: "Cuota mensual de membresía en pesos MXN" },
        { clave: "BANCO_NOMBRE",            valor: "Banorte",            desc: "Nombre del banco para transferencias" },
        { clave: "BANCO_NUMERO_CUENTA",     valor: "0001617086-5",       desc: "Número de cuenta bancaria" },
        { clave: "BANCO_CLABE",             valor: "072 580 00016170865 0", desc: "CLABE interbancaria" },
        { clave: "ASOCIACION_NOMBRE",       valor: "Asociación de Espina Bífida de Nuevo León, A.B.P.", desc: "Nombre oficial" },
      ];
      for (const { clave, valor, desc } of configs) {
        await conn.execute(
          `INSERT INTO CONFIGURACION (CLAVE, VALOR, DESCRIPCION) VALUES (:clave, :valor, :desc)`,
          { clave, valor, desc },
          { autoCommit: true }
        );
      }
      console.log("[migration-005] ✅ Tabla CONFIGURACION creada con valores iniciales.");
    }

  } catch (err) {
    console.error("[migration-005] ❌ Error:", err?.message ?? err);
  } finally {
    if (conn) await conn.close().catch(() => {});
  }
}
