DECLARE
  v_count NUMBER := 0;
BEGIN
  SELECT COUNT(*)
    INTO v_count
    FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME = 'MOVIMIENTOS_INVENTARIO'
     AND COLUMN_NAME = 'STOCK_RESULTANTE';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE MOVIMIENTOS_INVENTARIO ADD (STOCK_RESULTANTE NUMBER NOT NULL)';
  END IF;
END;
/
