-- Script preliminar de base de datos del proyecto EspinaBifida
-- Basado en entidades y relaciones utilizadas por el backend.

-- =====================================
-- 1) TABLAS BASE
-- =====================================

CREATE TABLE ROLES (
  ID_ROL       NUMBER       PRIMARY KEY,
  NOMBRE_ROL   VARCHAR2(100) NOT NULL,
  DESCRIPCION  VARCHAR2(255)
);

CREATE TABLE ADMINISTRADORES (
  ID_ADMIN         NUMBER         PRIMARY KEY,
  ID_ROL           NUMBER         NOT NULL,
  NOMBRE_COMPLETO  VARCHAR2(150)  NOT NULL,
  EMAIL            VARCHAR2(200)  NOT NULL,
  PASSWORD_HASH    VARCHAR2(255)  NOT NULL,
  ACTIVO           NUMBER(1)      DEFAULT 1 NOT NULL,
  FECHA_CREACION   DATE           DEFAULT SYSDATE NOT NULL,
  CONSTRAINT FK_ADMIN_ROL FOREIGN KEY (ID_ROL)
    REFERENCES ROLES(ID_ROL)
);

CREATE TABLE BENEFICIARIOS (
  CURP                  VARCHAR2(18)   PRIMARY KEY,
  NOMBRES               VARCHAR2(100)  NOT NULL,
  APELLIDO_PATERNO      VARCHAR2(100)  NOT NULL,
  APELLIDO_MATERNO      VARCHAR2(100)  NOT NULL,
  FECHA_NACIMIENTO      DATE           NOT NULL,
  GENERO                VARCHAR2(1),
  NOMBRE_PADRE_MADRE    VARCHAR2(150),
  CALLE                 VARCHAR2(150),
  COLONIA               VARCHAR2(150),
  CIUDAD                VARCHAR2(100),
  MUNICIPIO             VARCHAR2(100),
  ESTADO                VARCHAR2(100),
  CP                    VARCHAR2(5),
  TELEFONO_CASA         VARCHAR2(10),
  TELEFONO_CELULAR      VARCHAR2(10),
  CORREO_ELECTRONICO    VARCHAR2(150),
  CONTACTO_EMERGENCIA   VARCHAR2(150),
  TELEFONO_EMERGENCIA   VARCHAR2(10),
  MUNICIPIO_NACIMIENTO  VARCHAR2(100),
  HOSPITAL_NACIMIENTO   VARCHAR2(150),
  TIPO_SANGRE           VARCHAR2(3),
  USA_VALVULA           VARCHAR2(1)    DEFAULT 'N',
  NOTAS                 CLOB,
  ESTATUS               VARCHAR2(10)   DEFAULT 'Activo' NOT NULL,
  FECHA_ALTA            DATE           DEFAULT SYSDATE,
  CONSTRAINT CHK_BENEFICIARIOS_GENERO CHECK (GENERO IN ('M','F')),
  CONSTRAINT CHK_BENEFICIARIOS_VALVULA CHECK (USA_VALVULA IN ('S','N')),
  CONSTRAINT CHK_BENEFICIARIOS_ESTATUS CHECK (ESTATUS IN ('Activo','Inactivo','Baja'))
);

CREATE TABLE CREDENCIALES (
  ID_CREDENCIAL         NUMBER         PRIMARY KEY,
  CURP                  VARCHAR2(18)   NOT NULL,
  NUMERO_CREDENCIAL     VARCHAR2(50)   NOT NULL,
  FECHA_EMISION         DATE           NOT NULL,
  FECHA_VIGENCIA_INICIO DATE           NOT NULL,
  FECHA_VIGENCIA_FIN    DATE           NOT NULL,
  FECHA_ULTIMO_PAGO     DATE,
  OBSERVACIONES         VARCHAR2(500),
  CONSTRAINT FK_CREDENCIALES_BENEFICIARIO FOREIGN KEY (CURP)
    REFERENCES BENEFICIARIOS(CURP)
);

CREATE TABLE SERVICIOS_CATALOGO (
  ID_TIPO_SERVICIO NUMBER         PRIMARY KEY,
  NOMBRE           VARCHAR2(100)  NOT NULL,
  DESCRIPCION      VARCHAR2(255),
  ACTIVO           NUMBER(1)      DEFAULT 1 NOT NULL
);

CREATE TABLE SERVICIOS (
  ID_SERVICIO      NUMBER         PRIMARY KEY,
  CURP             VARCHAR2(18)   NOT NULL,
  ID_TIPO_SERVICIO NUMBER         NOT NULL,
  FECHA            DATE           DEFAULT SYSDATE NOT NULL,
  COSTO            NUMBER(10,2)   NOT NULL,
  MONTO_PAGADO     NUMBER(10,2)   DEFAULT 0 NOT NULL,
  REFERENCIA_ID    VARCHAR2(50),
  REFERENCIA_TIPO  VARCHAR2(50),
  NOTAS            CLOB,
  CONSTRAINT FK_SERVICIOS_BENEFICIARIO FOREIGN KEY (CURP)
    REFERENCES BENEFICIARIOS(CURP),
  CONSTRAINT FK_SERVICIOS_CATALOGO FOREIGN KEY (ID_TIPO_SERVICIO)
    REFERENCES SERVICIOS_CATALOGO(ID_TIPO_SERVICIO)
);

CREATE TABLE CITAS (
  ID_CITA           NUMBER         PRIMARY KEY,
  CURP              VARCHAR2(18)   NOT NULL,
  ID_TIPO_SERVICIO  NUMBER,
  ESPECIALISTA      VARCHAR2(150),
  FECHA             TIMESTAMP      NOT NULL,
  ESTATUS           VARCHAR2(20)   DEFAULT 'PROGRAMADA',
  NOTAS             CLOB,
  CONSTRAINT FK_CITAS_BENEFICIARIO FOREIGN KEY (CURP)
    REFERENCES BENEFICIARIOS(CURP),
  CONSTRAINT FK_CITAS_CATALOGO FOREIGN KEY (ID_TIPO_SERVICIO)
    REFERENCES SERVICIOS_CATALOGO(ID_TIPO_SERVICIO)
);

CREATE TABLE ARTICULOS (
  ID_ARTICULO         NUMBER         PRIMARY KEY,
  DESCRIPCION         VARCHAR2(200)  NOT NULL,
  UNIDAD              VARCHAR2(30),
  CUOTA_RECUPERACION  NUMBER(10,2)   DEFAULT 0 NOT NULL,
  INVENTARIO_ACTUAL   NUMBER         DEFAULT 0 NOT NULL,
  MANEJA_INVENTARIO   NUMBER(1)      DEFAULT 1 NOT NULL,
  ID_CATEGORIA        NUMBER,
  CONSTRAINT CHK_ARTICULOS_INVENTARIO CHECK (MANEJA_INVENTARIO IN (0,1))
);

CREATE TABLE MOVIMIENTOS_INVENTARIO (
  ID_MOVIMIENTO    NUMBER         PRIMARY KEY,
  ID_ARTICULO      NUMBER         NOT NULL,
  TIPO_MOVIMIENTO  VARCHAR2(10)   NOT NULL,
  CANTIDAD         NUMBER         NOT NULL,
  MOTIVO           VARCHAR2(255),
  FECHA            DATE           DEFAULT SYSDATE NOT NULL,
  CONSTRAINT FK_MOV_INV_ARTICULO FOREIGN KEY (ID_ARTICULO)
    REFERENCES ARTICULOS(ID_ARTICULO),
  CONSTRAINT CHK_MOV_INV_TIPO CHECK (TIPO_MOVIMIENTO IN ('ENTRADA','SALIDA')),
  CONSTRAINT CHK_MOV_INV_CANT CHECK (CANTIDAD > 0)
);

-- =====================================
-- 2) ÍNDICES RECOMENDADOS
-- =====================================

CREATE UNIQUE INDEX UQ_ADMINISTRADORES_EMAIL ON ADMINISTRADORES (EMAIL);
CREATE INDEX IX_CREDENCIALES_CURP ON CREDENCIALES (CURP);
CREATE INDEX IX_SERVICIOS_CURP ON SERVICIOS (CURP);
CREATE INDEX IX_SERVICIOS_TIPO ON SERVICIOS (ID_TIPO_SERVICIO);
CREATE INDEX IX_CITAS_CURP ON CITAS (CURP);
CREATE INDEX IX_MOVIMIENTOS_ARTICULO ON MOVIMIENTOS_INVENTARIO (ID_ARTICULO);

-- =====================================
-- 3) SECUENCIAS (SUGERIDAS)
-- =====================================

CREATE SEQUENCE SEQ_ADMINISTRADORES START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CREDENCIALES START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_ROLES START WITH 3 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_SERVICIOS_CATALOGO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_ARTICULOS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_SERVICIOS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CITAS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_MOVIMIENTOS_INV START WITH 1 INCREMENT BY 1 NOCACHE;

-- =====================================
-- 4) DATOS INICIALES MÍNIMOS
-- =====================================

INSERT INTO ROLES (ID_ROL, NOMBRE_ROL, DESCRIPCION) VALUES (1, 'Super Administrador', 'Acceso total');
INSERT INTO ROLES (ID_ROL, NOMBRE_ROL, DESCRIPCION) VALUES (2, 'Recepción', 'Operación diaria');

COMMIT;
